"""
FSM 模块处理器 — 管线执行 + next_node 节点跳转。

原 chat._run_pipeline 的 FSM 分支与 _handle_node_transition 原样迁移。
"""

import logging

from src.chat.context_lifecycle import TurnLifecycle
from src.chat.handlers.base import PipelineHandler
from src.chat.loop import TurnResult
from src.chat.session import Session

logger = logging.getLogger(__name__)

# FSM/ROUTE 转移阶段共用的增量合并入口（收敛原 chat 层两份重复拷贝）
_lifecycle = TurnLifecycle()


class FsmHandler(PipelineHandler):
    """FSM 模块一轮处理：节点解析 → R3 刷新 → stages → next_node 跳转。"""

    def handle(self, session: Session, module,
               force_close: bool = False) -> TurnResult:
        cxt = session.cxt
        pattern = session.pattern

        self._resolve_entry_node(cxt, module)

        # R3：节点解析完按 module+node 刷新 LLM 配置（spec §4）
        self.refresh_llm(session, module_code=module.module_code,
                         node_code=cxt.current_node_code)

        self._run_stages(cxt, module, pattern)

        # FSM：next_node 跳转（澄清轮守卫在转移函数内）
        fsm_node_transition(cxt, module)

        # Extract the reply generated by NLG
        nlg_result = cxt.nlg_result or {}
        response = nlg_result.get("content", "")

        return TurnResult(reply=response)


def fsm_node_transition(cxt, module) -> None:
    """FSM 轮末节点转移（原 chat._handle_node_transition 原样迁移）。

    按 NLU 结果的 next_node 跳转；澄清轮跳过槽位合并与跳转（topic/keywords
    不入 filled_slots，节点保持）。同时把 NLU 抽取的槽位增量合并进
    filled_slots。

    Args:
        cxt: dialogue context
        module: current module object
    """
    # 澄清轮：跳过槽位合并（topic/keywords 不入 filled_slots），节点保持
    if (cxt.metadata.get("clarify") or {}).get("triggered"):
        logger.info("澄清轮，跳过槽位合并与节点跳转: node=%s", cxt.current_node_code)
        return

    nlu_result = cxt.nlu_result or {}
    slots = nlu_result.get("slots", {})

    # Merge slots（增量：经 lifecycle 入口）
    _lifecycle.merge_slots(cxt, slots)

    # FSM type: jump according to next_node in the NLU result
    next_node_code = nlu_result.get("next_node", "")

    if not next_node_code:
        logger.info("NLU 未返回 next_node，保持当前节点: %s", cxt.current_node_code)
        return

    if next_node_code not in cxt.node_map:
        logger.warning(
            "NLU 返回的 next_node '%s' 不在 node_map 中，保持当前节点: %s",
            next_node_code,
            cxt.current_node_code,
        )
        return

    logger.info(
        "FSM 节点跳转: %s → %s",
        cxt.current_node_code,
        next_node_code,
    )
    cxt.current_node_code = next_node_code
