"""
ROUTE 模块处理器 — 管线执行 + jump_module 静默分发 / root 重置。

行为等价原 chat._run_pipeline 的 ROUTE 分支。
"""

import logging

from src.chat.context_lifecycle import TurnLifecycle
from src.chat.handlers.base import PipelineHandler
from src.chat.loop import TurnResult
from src.chat.session import Session
from src.dialogue.dispatch import ModuleDispatch, dispatch
from src.dialogue.module import ModuleType

logger = logging.getLogger(__name__)

_lifecycle = TurnLifecycle()


class RouteHandler(PipelineHandler):
    """ROUTE 模块一轮处理。

    流程：节点解析 → R3 刷新 → stages（含 _RouteNodeAdvance 菜单节点切换）
    → 槽位合并 → jump_module 静默分发（dispatch_event）或 root 重置 → 提取回复。
    """

    def handle(self, session: Session, module,
               force_close: bool = False) -> TurnResult:
        cxt = session.cxt
        pattern = session.pattern

        self._resolve_entry_node(cxt, module)

        # R3：节点解析完按 module+node 刷新 LLM 配置（spec §4）
        self.refresh_llm(session, module_code=module.module_code,
                         node_code=cxt.current_node_code)

        self._run_stages(cxt, module, pattern)

        if not force_close and not (cxt.metadata.get("clarify") or {}
                                    ).get("triggered"):
            cur_node = cxt.node_map.get(cxt.current_node_code)
            jump_target = getattr(cur_node, "jump_module", None) if cur_node else None

            # 槽位合并保留（增量：经 lifecycle 入口）
            slots = (cxt.nlu_result or {}).get("slots", {})
            _lifecycle.merge_slots(cxt, slots)

            if jump_target and jump_target in cxt.module_map:
                event = ModuleDispatch(
                    target_module_code=jump_target, source="route_menu")
                if dispatch(cxt, event):
                    # dispatch() 已完成状态转移；event 仅作日志供 chat 层消费。
                    # 若 stages 里 NLG 已生成 nlg_result，静默分发路径不消费它。
                    return TurnResult(dispatch_event=event)
                # dispatch 失败（不邻接/回弹）→ 回退正常 NLG 回复路径
        # ROUTE 轮末统一重置回 root（含 force_close：跳过 dispatch 但不留在菜单节点，
        # 否则菜单节点无 sub_nodes，下一轮路由候选为空；澄清轮不走此分支，节点保持）
        root_code = module.module_nodes[0].node_code if module.module_nodes else None
        if not (cxt.metadata.get("clarify") or {}).get("triggered"):
            cxt.current_node_code = root_code
            logger.info("ROUTE 模块保持 root 节点: %s", root_code)

        # Extract the reply generated by NLG
        nlg_result = cxt.nlg_result or {}
        response = nlg_result.get("content", "")

        return TurnResult(reply=response)
